# Generated by Django 5.0.4 on 2024-04-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AM', 'Amoxicillin'), ('AP', 'Amplodipine'), ('PC', 'Paracetamol')], max_length=2),
        ),
    ]
