# Generated by Django 5.0.4 on 2024-04-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_description_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AM', 'Amoxicillin'), ('AP', 'Amplodipine'), ('PC', 'Paracetamol'), ('AT', 'Atorvastatin'), ('BP', 'Brufen'), ('CC', 'Ciprofloxacin'), ('MF', 'Metformin'), ('MA', 'Metronidazole'), ('OM', 'Omeprazole'), ('PD', 'Panadol')], max_length=2),
        ),
    ]
