# Generated by Django 5.0.4 on 2024-04-24 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Kushtia', 'Kushtia'), ('Rajshai', 'Rajshai'), ('Khulna', 'Khulna'), ('Narayangonj', 'Naryangonj'), ('jessor', 'Jessor'), ('Natore', 'Natore'), ('Bogura', 'Bogura'), ('Tangail', 'Tangail'), ('Gazipur', 'Gazipur'), ('Barishal', 'Barishal')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
