# Generated by Django 5.0.4 on 2024-04-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Rangpur', 'Rangpur'), ('Chattogram', 'Chattogram'), ('Rajshai', 'Rajshai'), ('Khulna', 'Khulna'), ('Barishal', 'Barishal'), ('Myamanshing', 'Maymanshing')], max_length=200),
        ),
    ]
