# Generated by Django 5.0.4 on 2024-04-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='medicine',
            new_name='product',
        ),
    ]
